name: "Deploy to Skynet"
description: "Deploy your static webapp to Skynet"
branding:
  icon: "cloud"
  color: "green"
inputs:
  upload-dir:
    description: "Directory to upload"
    required: true
  github-token:
    description: "Github token used for including the skylink url in pull request"
    required: true
  registry-seed:
    description: "Seed that generates registry private key (optional, only if you want to update the registry entry with skylink)"
  registry-datakey:
    description: "Registry datakey to use when updating the registry entry"
    default: "skylink.txt"
outputs:
  skylink:
    description: "Uploaded resource skylink"
  skylink-url:
    description: "Uploaded resource skylink url on https://siasky.net"
runs:
  using: "node12"
  main: index.js
