name: Update Distributable

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Update dist/index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE_TO_COMMIT: dist/index.js
        run: |
          git diff --exit-code -s $FILE_TO_COMMIT && echo "$FILE_TO_COMMIT up-to-date" && exit 0
          export TODAY=$( date -u '+%Y-%m-%d' )
          export MESSAGE="chore: regenerate $FILE_TO_COMMIT for $TODAY"
          export SHA=$( git rev-parse ${{ github.ref }}:$FILE_TO_COMMIT )
          export CONTENT=$( base64 -i $FILE_TO_COMMIT )
          gh api --method PUT /repos/:owner/:repo/contents/$FILE_TO_COMMIT \
            --field message="$MESSAGE" \
            --field content="$CONTENT" \
            --field encoding="base64" \
            --field branch="${{ github.ref }}" \
            --field sha="$SHA"
      - name: Update dist/licenses.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE_TO_COMMIT: dist/licenses.txt
        run: |
          git diff --exit-code -s $FILE_TO_COMMIT && echo "$FILE_TO_COMMIT up-to-date" && exit 0
          export TODAY=$( date -u '+%Y-%m-%d' )
          export MESSAGE="chore: regenerate $FILE_TO_COMMIT for $TODAY"
          export SHA=$( git rev-parse ${{ github.ref }}:$FILE_TO_COMMIT )
          export CONTENT=$( base64 -i $FILE_TO_COMMIT )
          gh api --method PUT /repos/:owner/:repo/contents/$FILE_TO_COMMIT \
            --field message="$MESSAGE" \
            --field content="$CONTENT" \
            --field encoding="base64" \
            --field branch="${{ github.ref }}" \
            --field sha="$SHA"
